### PR TITLE
Fix bug with handleEvent not correctly handling stopPropagation

### PR DESCRIPTION
**Pull request by jonbretman**
* improve minification
* make private attributes more private by using Math.random() to generate the attribute name
* improve test coverage

### CODE REVIEW

**Comment by djmc** [comment]
I can't tell if you fixed the original bug in the title or not :/

**Comment by jonbretman** [comment]
@djmc @iprignano Lets do a quick in-person code review of this so I can explain.

**Comment by djmc** [comment]
:+1:

**Pull request merged**
